#!/usr/bin/env python3
x=int(input('Enter an integer operand: '))
y=int(input('Enter another integer operand: '))
print('{} + {} = {}'.format(x,y,x+y))
print('{} - {} = {}'.format(x,y,x-y))
print('{} * {} = {}'.format(x,y,x*y))
print('{} / {} = {}'.format(x,y,x/y))
print('{} // {} = {}'.format(x,y,x//y))
print('{} % {} = {}'.format(x,y,x%y))
print('{} ** {} = {}'.format(x,y,x**y))
print('{:08b} & {:08b} = {:08b}'.format(x,y,x&y))
print('{:08b} | {:08b} = {:08b}'.format(x,y,x|y))
print('{:08b} ^ {:08b} = {:08b}'.format(x,y,x^y))
print('{:08b} << {:08b} = {:08b}'.format(x,y,x<<y))
print('{:08b} >> {:08b} = {:08b}'.format(x,y,x>>y))
